---
abstract: 'A Perlish compact query language for ElasticSearch'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ElasticSearch-SearchBuilder
provides:
  ElasticSearch::SearchBuilder:
    file: lib/ElasticSearch/SearchBuilder.pm
    version: 0.04
requires:
  Scalar::Util: 0
resources:
  bugtracker: https://github.com/clintongormley/ElasticSearch-SearchBuilder/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/clintongormley/ElasticSearch-SearchBuilder/
version: 0.04
